function s = getStyle(height,width,render)
	s = struct;
	s.Version = '1';
	s.Format = 'eps';
	s.Preview = 'none';
	s.Width = width; % width
	s.Height = height;
	s.Units = 'centimeters';
	s.Color = 'rgb';
	s.Background = '[1 1 1]'; % white background
	s.FixedFontSize = '10';
	s.ScaledFontSize = 'auto';
	s.FontMode = 'fixed';
	s.FontSizeMin = '10';
	s.FixedLineWidth = 'auto';
	s.ScaledLineWidth = 'auto';
	s.LineMode = 'auto';
	s.LineWidthMin = '0.5';
	%s.FontName = 'Latin Modern Roman';
    s.FontName = 'Times New Roman'; 
	s.FontWeight = 'auto';
	s.FontAngle = 'auto';
	s.FontEncoding = 'latin1';
	s.PSLevel = '3';
	s.Renderer = render;
	s.Resolution = '600';
	s.LineStyleMap = 'none';
	s.ApplyStyle = '0';
	s.Bounds = 'loose';
	s.LockAxes = 'on';
	s.LockAxesTicks = 'off';
	s.ShowUI = 'on';
	s.SeparateText = 'off';
end